# Generated by Django 3.1.1 on 2020-09-04 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='follows',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_twitteruser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
